#!/bin/bash
export COLOR_CONTEXT=$PURPLE
export COLOR_TASKNUM='\\033[47m'
export COLOR_PROJECT=$LIGHT_BLUE
# export COLOR_PROJECT='<b>'
# export COLOR_PROJECT_END='<b>'
export COLOR_DATE=$CYAN
if [ "$TODOTXT_PLAIN" -eq "0" ]; then
awk --re-interval '
function highlight(colorVar,      color) {
    color = ENVIRON[colorVar]
    gsub(/\\+033/, "\033", color)
    return color
}
function highlightend(colorVar, defaultColor,      color) {
    color = highlight(colorVar "_END")
    if (color == "") {
        return defaultColor
    } else {
        return color
    }
}
function linehl(      hl) {
    if (match($0, /[0-9]+ /) > 1) {
        return substr($0, 1, RSTART - 1)
    } else {
        return highlight("DEFAULT")
    }
}
{
    color = linehl()
    if (! match($0, /[0-9]+ x /)) {
        $0 = gensub(/([0-9]+) /, highlight("COLOR_TASKNUM") "\\1" highlightend("COLOR_TASKNUM", color) " ", " ")
    }
    $0 = gensub(/ (@[^ ]*)/, " " highlight("COLOR_CONTEXT") "\\1" highlightend("COLOR_CONTEXT", color), "g")
    $0 = gensub(/ (\+[^ ]*)/, " " highlight("COLOR_PROJECT") "\\1" highlightend("COLOR_PROJECT", color), "g")
    $0 = gensub(/ ([0-9]{4}-[0-9]{2}-[0-9]{2}) /, " " highlight("COLOR_DATE") "\\1" color " ", "")
    print
}
'
else
cat
fi
