#!/bin/bash
awk --re-interval -v date=$1 '
BEGIN {
    if (date == "") {
        threshold = mktime(strftime("%Y %m %d 00 00 00", systime()))
    } else {
        threshold = mktime(gensub(/([0-9]{4})-([0-9]{2})-([0-9]{2})/, "\\1 \\2 \\3 00 00 00", "", date))
    }
}
/ t:[0-9]{4}-[0-9]{2}-[0-9]{2}( |$)/ {
    date = mktime(gensub(/^.* t:([0-9]{4})-([0-9]{2})-([0-9]{2})( .*)?$/, "\\1 \\2 \\3 00 00 00", ""))
    if (date <= threshold) {
        print
    }
    next
}
{ print }
'
