#!/bin/bash

# Attention: This filter is to be used in pre_filter_command, before formatting
# and coloring of priorities. It won't work as a TODOTXT_FINAL_FILTER! 
# Converts x:DUPITEM# marker into trashing of the task, with a corresponding
# comment (the same that "dup del" uses) appended. Useful as an alternative to
# "dup del" when editing in other clients. 

: ${TODOTXT_COMMENT_SYMBOL:= => }

awk --re-interval -v commentSymbol="$TODOTXT_COMMENT_SYMBOL" '
/ *[0-9]+ [xX] / {
    # Do not process done tasks. 
    print
    next
}
/ x:[0-9]+( |$)/ {
    today = strftime("%Y-%m-%d", systime())
    dupItem = gensub(/^.* x:([0-9]+).*$/, "\\1", "")
    $0 = gensub(/^( *[0-9]+ )(\(.\) )?/, "\\1X " today " ", "") commentSymbol "dup of " dupItem
}
{ print }
'
