#!/bin/bash

awk --re-interval -v action=$1 -v date=$2 '
function getThreshold(date) {
    if (date == "") {
        return mktime(strftime("%Y %m %d 00 00 00", systime()))
    } else {
        return mktime(gensub(/([0-9]{4})-([0-9]{2})-([0-9]{2})/, "\\1 \\2 \\3 00 00 00", "", date))
    }
}
BEGIN {
    threshold = getThreshold(date)
}
/^x / {
    # Do not process done tasks. 
    if (action == "clear") {
        print
    }
    next
}
/^X / {
    # Explicitly trashed task. 
    if (action == "filter") {
        print
    } else if (action == "clear") {
        print ""
    } else {
        print "ASSERT: Unknown action: " action
        exit 2
    }
    next
}
/(^| )x:[0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    date = mktime(gensub(/^(.* )?x:([0-9]{4})-([0-9]{2})-([0-9]{2})([^0-9].*)?$/, "\\1 \\2 \\3 00 00 00", ""))
    if (date <= threshold) {
        if (action == "filter") {
            print
        } else if (action == "clear") {
            print ""
        } else {
            print "ASSERT: Unknown action: " action
            exit 2
        }
        next
    }
}
{
    if (action == "clear") {
        print
    }
}'
