#!/bin/bash todo.txt configuration. 
#
# === EDIT FILE LOCATIONS BELOW ===

# Your todo.txt directory
#export TODO_DIR="/Users/gina/Documents/todo"
#export TODO_DIR="C:/Documents and Settings/gina/My Documents"
export TODO_DIR="$HOME/todo"

# Your todo/done/report.txt locations
export TODO_FILE="$TODO_DIR/todo.txt"
export DONE_FILE="$TODO_DIR/done.txt"
export REPORT_FILE="$TODO_DIR/report.txt"
export TMP_FILE="${TEMP:-/tmp}/todo.tmp"

# You can customize your actions directory location
#export TODO_ACTIONS_DIR="$HOME/.todo.actions.d"

# == EDIT FILE LOCATIONS ABOVE ===

# === COLOR MAP ===

## Text coloring and formatting is done by inserting ANSI escape codes.
## If you have re-mapped your color codes, or use the todo.txt
## output in another output system (like Conky), you may need to
## over-ride by uncommenting and editing these defaults.
## If you change any of these here, you also need to uncomment
## the defaults in the COLORS section below. Otherwise, todo.txt
## will still use the defaults!

# export BLACK='\\033[0;30m'
# export RED='\\033[0;31m'
# export GREEN='\\033[0;32m'
# export BROWN='\\033[0;33m'
# export BLUE='\\033[0;34m'
# export PURPLE='\\033[0;35m'
# export CYAN='\\033[0;36m'
# export LIGHT_GREY='\\033[0;37m'
# export DARK_GREY='\\033[1;30m'
# export LIGHT_RED='\\033[1;31m'
# export LIGHT_GREEN='\\033[1;32m'
# export YELLOW='\\033[1;33m'
# export LIGHT_BLUE='\\033[1;34m'
# export LIGHT_PURPLE='\\033[1;35m'
# export LIGHT_CYAN='\\033[1;36m'
# export WHITE='\\033[1;37m'
# export DEFAULT='\\033[0m'

# === COLORS ===

## Uncomment and edit to override these defaults.
## Reference the constants from the color map above,
## or use $NONE to disable highlighting.
#
# Priorities can be any upper-case letter.
# A,B,C are highlighted; you can add coloring for more.
#
export PRI_A='\\033[0;41m'
export PRI_B='\\033[0;44m'
export PRI_C='\\033[0;46m'
# export PRI_D=...            # define your own
export PRI_X=$PURPLE         # color unless explicitly defined

# There is highlighting for tasks that have been done,
# but haven't been archived yet.
#
export COLOR_DONE=$PURPLE
export COLOR_TRASH=$LIGHT_GREY

# Do not highlight the add date, it's not that important, always at the same
# place, and the coloring interferes with the relativeDates filter. 
export COLOR_DATE=

# Customize some colors in a high-color terminal. 
if [ ${TERM_COLORS:-0} -ge 256 ]; then
    export PRI_A=$DEFAULT'\\033[48;5;196m'
    export PRI_B=$DEFAULT'\\033[48;5;39m'
    export PRI_C=$DEFAULT'\\033[48;5;51m'

    export COLOR_DONE=$DEFAULT'\\033[38;5;242m'

    export COLOR_PROJECT='\\033[01;38;5;19m'
    export COLOR_CONTEXT='\\033[01;38;5;90m'
    export COLOR_ALTERNATING=$DEFAULT'\\033[48;5;255m'
fi

# === BEHAVIOR ===
[ "$HIDE_COLOR_DONE"  ] && unset COLOR_DONE
[ "$HIDE_COLOR_TRASH" ] && unset COLOR_TRASH


# Do not automatically archive tasks on completion; I want to do this manually
# (e.g. at the beginning of a new day). 
export TODOTXT_AUTO_ARCHIVE=0

# Prepend the date to any added task so that I can track the duration the task
# was open. 
export TODOTXT_DATE_ON_ADD=1

# Default action is showing all prioritized and due tasks. 
export TODOTXT_DEFAULT_ACTION=what

## customize list output
#
# TODOTXT_SORT_COMMAND will filter after line numbers are
# inserted, but before colorization, and before hiding of
# priority, context, and project.
#
# export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -f -k2'
# Sort only on the second column (containing the priority or first project,
# after the todo number)
export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -f -k2,2'

# TODOTXT_FINAL_FILTER will filter list output after colorization,
# priority hiding, context hiding, and project hiding. That is,
# just before the list output is displayed.
#
# export TODOTXT_FINAL_FILTER='cat'
# First filter out future tasks, based on markers of the form "t:YYYY-MM-DD",
# and color tasks with due and latest dates. 
# Then, convert near dates to relative ones, e.g. "yesterday". 
# Finally, color task numbers, projects and contexts. 
export TODOTXT_FINAL_FILTER="$HOME/.todo/colorFutureTasks | $HOME/.todo/relativeDates | $HOME/.todo/colorSymbols"

# Implement scheduled priorization and de-priorization via a custom filter that
# executes before the main filtering, so that it does not interfere with a
# post_filter_command used by various addons, and so that the projected priority
# is considered by actions that do filtering on _list output. 
export pre_filter_command="$HOME/.todo/scheduledFilter"

# Make 'what' addon show only priorities A-F. 
export TODOTXT_WHAT_PRIORITIES=A-F

# Additional addons that handle multiple ITEM# arguments. 
export TODOTXT_TASKS_MULTIACTIONS='del depri did do dp dup ls mail nav pri schedule trash undo until untrash unwait wait'

# Use extended human date specifications for the "date" command when available. 
if which dateex >/dev/null 2>&1; then
    # Install the extended command via an exported function. 
    date()
    {
        exec dateex "$@"
    }
    export -f date
fi
