#!/bin/bash
###############################################################################
##
# FILE:         add
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 26-Dec-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2023 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEED TO DO t:tomorrow u:(next week)\""
    echo "      Adds THING I NEED TO DO to your todo.txt file on its own line."
    echo "      Dates in m: markers can be specified in various formats and will be"
    echo "      canonicalized to YYYY-MM-DD."
    echo ""
    exit
}

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }

# Note: We only offer the canonicalization of the date for add and actions based
# on add, but not for all other actions that modify tasks (e.g. append, replace,
# etc.) This is meant as a convenient shortcut when adding new tasks; existing
# task markers should be modified through dedicated actions (e.g. schedule).
task="${TODOTXT_ADD_PREFIX:-}${*}${TODOTXT_ADD_SUFFIX:-}"

TOTAL=$("${GNU_PREFIX}"sed -n '$ =' "$TODO_FILE") || exit $?
task="$("${scriptDir}/renderrelativemarkers" --task "$((TOTAL+1))" "$task")" || exit $?

# Translate @here to the actual lowercased hostname.
hostname="$TODOTXT_HOSTNAME"
if [ -n "$hostname" ]; then
    literalHostname="$(echo "$hostname" | tr '[:upper:]' '[:lower:]')"
    literalHostname="${literalHostname//\\/\\\\}"
    literalHostname="${literalHostname//&/\\&}"
    task="$(printf %s "$task" | "${GNU_PREFIX}"sed -e 's#\(^\|[[:space:]]\)@here\([[:space:]]\|$\)#'\\1"@${literalHostname//#/\\#}\\2#g")"
fi

"$TODO_FULL_SH" command ${TODOTXT_ADD_ACTION:-add} "$task"
