#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEED TO DO t:tomorrow u:(next week)\""
    echo "      Adds THING I NEED TO DO to your todo.txt file on its own line."
    echo "      Dates in m: markers can be specified in various formats and will be"
    echo "      canonicalized to YYYY-MM-DD."
    echo ""
    exit
}

task=$*
markers=$(echo "$task" | grep -o '[^ ]*[[:graph:]]:\([^ ]\+\|([^)]\+)\)' | grep '^[[:graph:]]:')
IFS=$'\n'
for marker in $markers
do
    dateString=${marker#[[:graph:]]:}
    dateString=${dateString#(}
    dateString=${dateString%)}

    if [[ "$dateString" =~ ^[0-9]+$ ]]; then
        # 'date' also accepts numbers (and always interprets them as the current
        # day), but numbers should represent ITEM# for task references here. 
        continue
    fi
    canonicalDate=$(date -d "$dateString" +%F 2>/dev/null) || continue
    [ "$canonicalDate" = "$dateString" ] && continue


    task=${task/${marker}/${marker:0:2}${canonicalDate}}
done
unset IFS

eval '"$TODO_FULL_SH" command' ${ADDACTION:-add} '"$task"'
