#!/bin/bash
###############################################################################
##
# FILE:         addagain
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 29-May-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addagain	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Adds a done task specified by TERM(s) as an open task again."
    echo "      When multiple tasks are found, queries which task to choose."
    echo ""
    exit
}

stripRawTasks()
{
    # Strip the task number, done marker, done and optional add dates.
    # Strip any m:DATE markers; they are probably obsolete.
    sed -e 's|^[0-9]\+ [xX]\( [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}\)\{1,2\} ||' \
        -e 's/ [[:graph:]]:[0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}//g'
}

addTask()
{
    "$TODO_FULL_SH" add "$@" || exit $?
    if [ -x "$TODO_ACTIONS_DIR/uncomment" ]; then
        # Figure out the line of what we just added, and "uncomment" it.
        item=$(sed -n '$ =' "$TODO_FILE")
        "$TODO_FULL_SH" uncomment -q "$item"
    fi
}

doneTasks=$(TODOTXT_VERBOSE=0 "$TODO_FULL_SH" -p -x lsdone "$@" | stripRawTasks | uniq)
if [ ! "$doneTasks" ]; then
    die "TODO: No tasks found."
fi
doneTasksNum=$(echo "$doneTasks" | wc -l)
if [ $doneTasksNum -eq 1 ]; then
    addTask "$doneTasks"
else
    echo "TODO: $doneTasksNum done tasks found."

    IFS=$'\n'
    for task in $(echo "$doneTasks" | tac)
    do
        echo
        echo "$task"
        read -p "Add task? ([o]nly this/[y]es/[n]o/[q]uit) " answer
        case $answer in
            o)  addTask "$task"
                break
                ;;
            y)  addTask "$task";;
            n)  ;;
            q)  exit;;
            *)  exit 2;;
        esac
    done
fi
