#!/bin/bash
###############################################################################
##
# FILE:         adddo
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 27-May-2010
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)adddo	001	(24-Feb-2012)	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEEDED TO DO RIGHT NOW\""
    echo "      Add a task and mark it as done in one step."
    echo ""
    exit
}

# call back to the main script to add
if "$TODO_FULL_SH" command add "$@"; then
    # figure out the line of what we just added, and "do" it
    line=$(sed -n '$ =' "$TODO_FILE")
    "$TODO_FULL_SH" command do "$line"
fi
