#!/usr/bin/env bash
###############################################################################
##
# FILE:         addendum
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 26-Dec-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addendum	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEED TO DO +project @context\""
    echo "      Adds a new task to add.txt. Use this when you know that todo.txt"
    echo "      on your system isn't up-to-date, and use \"todo.sh incorporate\" after"
    echo "      having sync'ed up with the latest version."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) \"THING I NEED TO DO +project @context\""
[ $# -eq 0 ] && die "$errmsg"

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

if [ -x "${scriptDir}/add" ]; then
    export TODOTXT_ADD_ACTION='addto add.txt'
    "${scriptDir}/add" addendum "$@"
else
    "$TODO_FULL_SH" addto add.txt "$@"
fi
