#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEED TO DO +project @context\""
    echo "      Adds a new task to add.txt. Use this when you know that todo.txt"
    echo "      on your system isn't up-to-date, and use \"todo.sh incorporate\" after"
    echo "      having sync'ed up with the latest version."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) \"THING I NEED TO DO +project @context\""
[ $# -eq 0 ] && die "$errmsg"

"$TODO_FULL_SH" addto add.txt "$@"
