#!/bin/bash
###############################################################################
##
# FILE:         addlike
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 08-May-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012-2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addlike	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [NR] THING SIMILAR TO NR"
    echo "      Adds THING SIMILAR TO NR, including the project(s) and context(s) from"
    echo "      line NR or, if omitted, the last task in todo.txt."
    echo ""
    exit
}

shopt -s extglob

errmsg="usage: $TODO_SH $(basename $0) [NR] THING SIMILAR TO NR"
item=
if [[ "$1" = +([0-9]) ]]; then
    # We got a NR.
    item=$1
    shift
else
    # Figure out the last line.
    item=$(sed -n '$ =' "$TODO_FILE") || exit $?
fi
getTodo "$item"

front=${todo% [^+@]*}
back=${todo#"${front}"}

keepers()
{
    printf %s "$1" | grep -o '[^ ]*[+@][^ ]\+' | grep '^[+@]'
}

"$TODO_FULL_SH" add $(keepers "$front") "$@" $(keepers "$back")
