#!/usr/bin/env bash
###############################################################################
##
# FILE:         addm
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ed Blackman
# MAINTAINER:   Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 17-Aug-2010
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# SOURCE:
#   Posted on the todo.txt mailing list:
#   http://tech.groups.yahoo.com/group/todotxt/message/2723
#
# @(#)addm	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    addm [-b prefix] [-e suffix] \"FIRST THING I NEED TO DO +project1 @context"
  echo "    SECOND THING I NEED TO DO +project2 @context\""
  echo "    printf '%s\n' {FIRST,SECOND}\" THING I NEED TO DO\" | $TODO_SH $(basename $0) -"
  echo "      Adds FIRST THING I NEED TO DO to your todo.txt on its own line and"
  echo "      Adds SECOND THING I NEED TO DO to you todo.txt on its own line."
  echo "      Project and context notation optional."
  echo "      Quotes optional."
  echo "      -b prefix adds \"prefix\" to the beginning of each line"
  echo "      -e suffix adds \"suffix\" to the end of each line"
  echo ""
  exit
}

# evaluate standardized arguments to set prefix and suffix
prefix=''
suffix=''

while getopts ":b:e:" opt; do
  case "$opt" in
    'b') prefix="$OPTARG ";;
    'e') suffix=" $OPTARG";;
  esac
done
shift $((OPTIND - 1))

if [ "$*" = - ]; then
    tasks="$(</dev/stdin)"
else
    tasks="$*"
fi

# Combine with configured prefixes and suffixes and render everything here, so
# that those apply to each item, not just the first / last one, respectively.
prefix="${TODOTXT_ADD_PREFIX}${prefix}"; TODOTXT_ADD_PREFIX=''
suffix="${suffix}${TODOTXT_ADD_SUFFIX}"; TODOTXT_ADD_SUFFIX=''
items="${prefix}${tasks//$'\n'/${suffix}$'\n'${prefix}}${suffix}"

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

if [ -x "${scriptDir}/add" ]; then
  export TODOTXT_ADD_ACTION='addm'
  "${scriptDir}/add" addm "$items"
else
  # Call back to the main script to addm.
  "$TODO_FULL_SH" command addm "$items"
fi
