#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    $(basename $0) PRIORITY \"THING I NEED TO DO +project @context\""
  echo "      Add a task and prioritize it in one step."
  echo ""
  exit
}

if [[ "$1" = [a-zA-Z] ]]; then
    pri=$1
    shift
fi

# call back to the main script to add
if "$TODO_FULL_SH" command add "$@"; then
    # figure out the line of what we just added, and prioritize it
    line=`sed -n '$ =' "$TODO_FILE"`
    "$TODO_FULL_SH" command pri "$line" $pri
fi
