#!/usr/bin/env bash
###############################################################################
##
# FILE:         addprereq
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 19-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012-2013 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addprereq	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR [NR ...] \"THING DEPENDING ON NR\""
    echo "      Adds THING DEPENDING ON NR, and marks them as depending on NR."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] \"THING DEPENDING ON NR\""

typeset -a depitems=()
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    depitems+=("$1")
    shift
done
[ ${#depitems} -gt 0 ] || die "$errmsg"

# Call back to the main script to add.
"$TODO_FULL_SH" add "$@" || exit $?

# Figure out the line of what we just added, and make it wait.
item=$(sed -n '$ =' "$TODO_FILE") || exit $?
"$TODO_FULL_SH" wait "$item" for "${depitems[@]}"
