#!/bin/bash
###############################################################################
##
# FILE:         addstart
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012-2013 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addstart	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I NEED TO DO +project @context\""
    echo "      Add a task and start working on it in one step."
    echo ""
    exit
}

# Call back to the main script to add.
"$TODO_FULL_SH" add "$@" || exit $?

# Figure out the line of what we just added, and prioritize it.
item=$(sed -n '$ =' "$TODO_FILE") || exit $?
"$TODO_FULL_SH" start "$item"
