#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    archive KEYWORD"
    echo "      Moves done tasks containing KEYWORD from todo.txt to done.txt and removes"
    echo "      blank lines."
    echo "    archive ITEM#"
    echo "      Moves task number ITEM# and removes blank lines."
    echo "      Note that if KEYWORD is a number it is considered as an ITEM# number"
    echo ""
    exit
}

if [[ "$1" =~ ^[0-9]+$ ]]; then
    item=$1 # we got a task to archive
    what="$item"
    [ $TODOTXT_VERBOSE -gt 0 ] && sed "$item!d" "$TODO_FILE"
    sed "$item!d" "$TODO_FILE" >> "$DONE_FILE"
    sed -i.bak $item"s/^.*//" "$TODO_FILE"
else
    keyword=$1 # we got a keyword, or nothing
    what="$(grep -c "^x .*$keyword" "$TODO_FILE") task(s)"
    [ $TODOTXT_VERBOSE -gt 0 ] && TODOTXT_VERBOSE=0 TODOTXT_DISABLE_FILTER=1 _list "$TODO_FILE" "^ *[0-9]\+ x .*$keyword" "$@"
    grep "^x .*$keyword" "$TODO_FILE" >> "$DONE_FILE"
    sed -i.bak "/^x .*$keyword/s/^.*//" "$TODO_FILE"
fi
[ $TODOTXT_VERBOSE -gt 0 ] && echo "TODO: $what archived."

if [ $# -eq 0 ]; then
    # This is a complete, regular archive. 
    # Use this occasion to make a backup. 
    if type -P writebackup.sh >/dev/null; then
        writebackup.sh "$TODO_FILE"
    fi
fi

# Defragment blank lines. 
if [ -x "$TODO_ACTIONS_DIR/defragment" ]; then
    # We have a customized defragment script that not only removes the empty
    # lines, but also adapts cross-task references; use it. 
    "$TODO_FULL_SH" defragment
else
    sed -i.bak -e '/./!d' "$TODO_FILE"
fi
