#!/bin/bash
###############################################################################
##
# FILE:         birdseye
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 19-Mar-2024
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)birdseye	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [(open|completed|all)-(projects|contexts) [...]]"
    echo "      Show a textual report of open and completed tasks"
    echo "      for all projects and contexts."
    echo ""
    exit
}

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
readonly projectDir="${scriptDir}/.."
readonly libDir="${projectDir}/lib"

"${libDir}/birdseye.py" "$@"; status=$?
if [ $status -eq 2 ]; then
    echo
    "${BASH_SOURCE[0]}" usage
fi >&2
exit $status
