#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    birdseye"
  echo "      Generates a textual report of pending and completed tasks"
  echo "      in all projects and contexts"
  echo ""
  exit
}

python ~/.todo/birdseye.py all all "$TODO_FILE" "$DONE_FILE"
