#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all waiting tasks grouped by blocker (wait reason, w:... marker)."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

readonly taskNum=$( sed -n '$ =' "$TODO_FILE" )
readonly taskNumWidth=${#taskNum}
padTaskNumber()
{
    printf "%0${taskNumWidth}d" $1
}

original_TODOTXT_VERBOSE=$TODOTXT_VERBOSE
TODOTXT_VERBOSE=0

# Show wait reasons in alphabetical order and blocked tasks in priority order. 
let blockerCnt=0
let dependentTaskCnt=0
let invalidDependentTaskCnt=0
tasksOnBlocker=
tasksOnDependentTask=

# Find all wait markers and sort. 
IFS=$'\n'
for waitMarker in $(sed -e '/^x /d' -e '/ w:/!d' -e 's/ w:[^ ]/\n&/g' "$TODO_FILE" | sed -n -e 's/^.* \(w:([^)]*)\).*$/\1/p;t' -e 's/^.* \(w:[^ ]*\).*$/\1/p' | sort -u )
do
    blocker=$(echo "$waitMarker" | sed -e 's/w:(\([^)]*\))/\1/' -e 's/w:\([^ ]*\)/\1/') 

    if [[ "$blocker" =~ ^[0-9]+$ ]]; then
        # Translate dependent task number into a shortened task description. 
        deptodo=$(sed -e "$blocker!d" -e 's/ \([[:alpha:]]:\|[+@]\)[^[:space:]]\+//g' -e 's/^\(([A-Z]) \)\{0,1\}\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}//g' "$TODO_FILE")
        if [ ! "$deptodo" ]; then
            deptodo='???'
            let invalidDependentTaskCnt+=1
        fi
        blocker="$(padTaskNumber $blocker) $deptodo"
        isTaskDependency='true'
    else
        isTaskDependency=
    fi

    # Extract all tasks that contain the waitMarker and remove the marker itself
    # before any final filter performs highlighting. 
    post_filter_command="sed -e '/ ${waitMarker}/!d' -e 's/ ${waitMarker}//g'"
    waitList=$(_list "$TODO_FILE" "$@")
    if [[ -n "$waitList" ]]; then
        echo "--- $blocker ---"
        echo "$waitList"
        echo ""

        if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
            if [ "$isTaskDependency" ]; then
                let dependentTaskCnt+=1
                tasksOnDependentTask="${tasksOnDependentTask}${tasksOnDependentTask:+
}${waitList}"
            else
                let blockerCnt+=1
                tasksOnBlocker="${tasksOnBlocker}${tasksOnBlocker:+
}${waitList}"
            fi
        fi
    fi
done

if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
    let taskOnBlockerCnt=$(echo "$tasksOnBlocker" | sort -u | sed -n '$ =')
    let taskOnDependentTaskCnt=$(echo "$tasksOnDependentTask" | sort -u | sed -n '$ =')

    echo "--"
    if [ $blockerCnt -gt 0 ]; then
        echo "TODO: $taskOnBlockerCnt blocked task(s) waiting for $blockerCnt blocker(s)."
    fi
    if [ $dependentTaskCnt -gt 0 ]; then
        echo "TODO: $taskOnDependentTaskCnt blocked task(s) waiting for $dependentTaskCnt dependent task(s)."
    fi
    if [ $blockerCnt -eq 0 -a $dependentTaskCnt -eq 0 ]; then
        echo "TODO: No blockers or dependent tasks found."
    fi
fi

if [ $invalidDependentTaskCnt -eq 1 ]; then
    echo "TODO: The list contains a dependency to an invalid task (marked ???)."
elif [ $invalidDependentTaskCnt -gt 1 ]; then
    echo "TODO: The list contains $invalidDependentTaskCnt dependencies to invalid tasks (marked ???)."
fi
