#!/bin/bash
###############################################################################
##
# FILE:         clone
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 29-Sep-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)clone	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# [PATTERN REPLACEMENT ...]"
    echo "      Clones ITEM# into a new task and replaces PATTERN with REPLACEMENT."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM# [PATTERN REPLACEMENT ...]"
item=$1; shift

[ -z "$item" ] && die "$errmsg"
[[ "$item" = +([0-9]) ]] || die "$errmsg"
# Get task without potential priority and prepended date.
todo=$(sed -e "$item!d" -e 's/^\((.) \)\{0,1\}\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}//' "$TODO_FILE")
[ -z "$todo" ] && die "TODO: No task $item."

"$TODO_FULL_SH" add "$todo"
clonedItem=$(sed -n '$ =' "$TODO_FILE")
"$TODO_FULL_SH" subst $clonedItem "$@"
