#!/bin/bash
###############################################################################
##
# FILE:         conflate
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 17-Jul-2013
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2013 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)conflate	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) KEEPITEM# ITEM#[, ITEM#, ...] [CONJUNCTION]"
    echo "      Combines ITEM# with KEEPITEM# (concatenated [with CONJUNCTION]) and"
    echo "      deletes all ITEM#. Duplicate projects and contexts are removed."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) KEEPITEM# ITEM#[, ITEM#, ...] [CONJUNCTION]"
[ $# -eq 0 ] && die "$errmsg"

keepitem=$1
shift
[[ "$keepitem" =~ ^[0-9]+$ ]] || die "$errmsg"

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    [ "$1" = ',' ] && break # Don't swallow a single comma, it's likely the CONJUNCTION.
    items="$items $1"
    shift
done
[ "$items" ] || die "$errmsg"

conjunction=' '
if [ $# -gt 0 ]; then
    if [[ "$1" =~ ^[[:alpha:]] ]]; then
        conjunction=" $* "
    else
        conjunction="$* "
    fi
fi


getTodo "$keepitem"
combinedTodo=$todo

# Append the additional task(s) with removed existing priority, done marker, and prepended date(s).
readonly pruneExpr='^\([xX] \|(.) \)\{0,1\}\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,2\}'
for item in ${items//,/ }
do
    getTodo "$item"
    prunedTodo=$(echo "$todo" | sed -e "s/${pruneExpr}//")
    combinedTodo="${combinedTodo}${conjunction}${prunedTodo}"
done

# Filter duplicate +project and @context occurrences.
filteredCombinedTodo=$(echo "$combinedTodo" | sed -e ':recurse' -e 's/\(^\| \)\([+@][^ ]\+\)\( .*\)\2\( \|$\)/\1\2\3/' -e 't recurse')


# Replace the kept task with the combined one.
# The 'replace' command doesn't handle done tasks, and may do
# surprising things to existing priorities and dates. To avoid surprises,
# do the complete replacement of the line here.
input=$filteredCombinedTodo
cleaninput "for sed"
sed -i.bak "$keepitem s|^.*|${input}|" "$TODO_FILE" || exit $?
if [ $TODOTXT_VERBOSE -gt 0 ]; then
    echo "TODO: Combined tasks into:"
    echo "$keepitem $filteredCombinedTodo"
fi

# Remove all other task(s).
for item in ${items//,/ }
do
    "$TODO_FULL_SH" -f del $item
done
