#!/bin/bash
# 2009 Paul Mansfield
# License:  GPL, http://www.gnu.org/copyleft/gpl.html

action=$1
shift

if [ "$action" = "usage" ]; then
    echo "    $(basename $0) [TERM...]"
    echo "      Show tasks containing TERM, grouped by context, and displayed in"
    echo "      priority order. If no TERM provided, displays entire todo.txt."
    echo ""
    exit
fi

# Configuration to only summarize many unassociated tasks. 
: TODOTXT_CONTEXTVIEW_UNASSOCIATED_THRESHOLD=${TODOTXT_CONTEXTVIEW_UNASSOCIATED_THRESHOLD:=10}

original_TODOTXT_VERBOSE=$TODOTXT_VERBOSE
TODOTXT_VERBOSE=0

# Show contexts in alphabetical order and tasks in priority order. 
let contextCnt=0
tasks=

# Find all contexts. 
readonly contexts=$(eval "$(filtercommand 'cat "$TODO_FILE"' '' "$@")" | grep -o '[^ ]*@[^ ]\+' | grep '^@' | sort -u)

# For each context show header and the list of tasks. 
export HIDE_CONTEXTS_SUBSTITUTION='[[:space:]]@[[:graph:]]\{1,\}'   # Omitting all contexts from the list. 
for context in $contexts; do 
    # Use core _list function, does numbering and coloring for us. 
    contextList=$(_list "$TODO_FILE" "$context\( \|$\)" "$@")
    if [ "$contextList" ]; then # Even though we're operating only on context tasks containing TERM, a task filter may still filter away all tasks for a context. 
        [ $contextCnt -gt 0 ] && echo ""
        echo "--- ${context} ---"
        echo "${contextList}"

        if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
            let contextCnt+=1
            tasks="${tasks}${tasks:+
}$contextList"
        fi
    fi
done

# Show tasks not associated with a context 
unassociatedCnt=0
contextList=$(_list "$TODO_FILE" "-[[:space:]]@[[:graph:]]" "$@")
if [ "$contextList" ]; then
    unassociatedCnt=$(echo "$contextList" | sed -n '$ =')
    if [ $unassociatedCnt -le $TODOTXT_CONTEXTVIEW_UNASSOCIATED_THRESHOLD ]; then
        [ $contextCnt -gt 0 ] && echo ""
        echo "--- Without context ---"
        echo "${contextList}"
    fi
fi

if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
    let TASK_CNT=$(echo "$tasks" | sort -u | sed -n '$ =')

    echo "--"
    if [ $contextCnt -gt 0 ]; then
        echo "TODO: $TASK_CNT task(s) with $contextCnt contexts."
    else
        echo "TODO: No contexts found."
    fi

    if [ $unassociatedCnt -gt $TODOTXT_CONTEXTVIEW_UNASSOCIATED_THRESHOLD ]; then
        echo "TODO: $unassociatedCnt task(s) without context."
    fi
fi
