#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0)"
    echo "      Cleans empty lines from todo.txt while adapting cross-task references"
    echo "      of the form w:### or \"task ###\". "
    echo ""
    exit
}

referencePattern='^w:[0-9]+$'

# Defragment blank lines. 
for emptyLineNum in $(sed -n '/./!=' "$TODO_FILE")
do
    awk -v referencePattern=$referencePattern -v lineNum=$emptyLineNum '
        function adapt(oldNum, oldLength,     newNum) {
            if (oldNum > lineNum) {
                newNum = sprintf("%0" oldLength "d", oldNum - 1)
                return newNum
            } else if (oldNum == lineNum) {
                return "???"
            } else {
                return oldNum
            }
        }
        BEGIN { FS = "[ \t]" }
        NR == lineNum { next }
        {
            for (i = 1; i <= NF; ++i) {
                if ($i ~ referencePattern) {
                    match($i, /[0-9]+/)
                    oldNum = substr($i, RSTART, RLENGTH) + 0
                    sub(/[0-9]+/, adapt(oldNum, RLENGTH), $i)
                } else if ($(i - 1) == "task" && $i ~ /^[0-9]+$/) {
                    oldNum = $i + 0
                    $i = adapt(oldNum, length($i))
                }
            }
        }; 1' \
        "$TODO_FILE" > "${TODO_FILE}.bak" && mv "${TODO_FILE}.bak" "${TODO_FILE}" || die "Fatal Error: Unable to process tasks."
done
