#!/bin/bash
###############################################################################
##
# FILE:         del
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 29-Sep-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2023 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)del	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [TERM]"
    echo "      Deletes the task(s) on line ITEM# in todo.txt."
    echo "      Task(s) that were dependent on ITEM# have that blocker removed."
    echo "      If TERM specified, deletes only TERM from the task."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [TERM]"
[ $# -eq 0 ] && die "$errmsg"

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items+=" $1"; shift
done
[ "$items" ] || die "$errmsg"

for item in ${items//,/ }
do
    "$TODO_FULL_SH" command del $item "$@" || exit $?

    # added by JCD to accomodate for notes
    [ $? -eq 0 ] && [ -z "$3" ] && "$TODO_SH" note __rmfromtext "DDDD$item"
    # end of added by JCD to accomodate for notes

    if [ $# -eq 0 -a -x "$TODO_ACTIONS_DIR/unwait" ]; then
        # Unblock tasks that depended on the deleted task.
        "$TODO_FULL_SH" unwait 'for' $item 2>&1 | grep -v '^TODO: No tasks that contain the dependent tasks found.$'
        : # Always exit with a successful exit code even when the command complained.
    fi
done

# Extend the auto-archiving to mean "no fluff" and therefore also trigger on
# deletions of entire tasks.
# Note: We could just invoke the defragment action here, but archive is more
# consistent and would also clean up tasks that have been done without
# auto-archiving or via a manual edit.
if [ -z "$*" -a $TODOTXT_AUTO_ARCHIVE = 1 ]; then
    "$TODO_FULL_SH" archive
fi
