#!/usr/bin/env bash
###############################################################################
##
# FILE:         did
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 07-Jan-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)did	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR [NR ...] [on] DATE [COMMENT]"
    echo "      Marks task(s) on line NR as done at DATE in todo.txt,"
    echo "      optionally appending COMMENT."
    echo "    $(basename $0) NR [NR ...] after DATESPAN [COMMENT]"
    echo "      Marks task(s) on line NR as done DATESPAN later than the added date,"
    echo "      optionally appending COMMENT."
    echo "    $(basename $0) NR [NR ...] the same|next day [COMMENT]"
    echo "      Marks task(s) on line NR as done on the same/next day they were added."
    echo "      Task(s) that were dependent on NR have that blocker removed."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] [on] DATE | after DATESPAN | the same|next day [COMMENT]"
[ $# -eq 0 ] && die "$errmsg"

if [ "$1" = --launch ]; then
    shift
    [ -n "${TODOTXT_DID_DATE+t}" ] || { echo >&2 'ASSERT: TODOTXT_DID_DATE is defined'; exit 3; }
    [ -n "${TODOTXT_DID_DATESPAN+t}" ] || { echo >&2 'ASSERT: TODOTXT_DID_DATESPAN is defined'; exit 3; }

    for item in ${*//,/ }
    do
        if [ -z "$TODOTXT_DID_DATE" ]; then
            addDate=$(sed -e "$item!d" -e 's/^\((.) \|x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}\(\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}\) \)\{0,1\}.*$/\3/' "$TODO_FILE")
            if [ ! "$addDate" ]; then
                die "TODO: Cannot use date span; no date was included when $item was added."
            fi
            TODOTXT_DID_DATE=$(date -d "${addDate}${TODOTXT_DID_DATESPAN:+ }${TODOTXT_DID_DATESPAN}" +%F) || exit 1
        fi

        getTodo "$item"
        # Do not check if this item has already been done; this allows
        # retroactive changes to the done date.
        # remove priority once item is done
        sed -i.bak $item"s/^(.) //" "$TODO_FILE" || exit $?
        sed -i.bak $item's|^\(x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}|'"x $TODOTXT_DID_DATE |" "$TODO_FILE" || exit $?
        if [ $TODOTXT_VERBOSE -gt 0 ]; then
            getNewtodo "$item"
            echo "$item $newtodo"
            echo "TODO: $item marked as done on ${TODOTXT_DID_DATE}."
        fi
    done
    exit 0
fi

items=
doneDate=
doneDateSpan=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items+=" $1"; shift
done
[ "$items" ] || die "$errmsg"

if [ "$1" = 'after' ]; then
    shift
    [ "$1" ] || die "$errmsg"
    doneDateSpan=$1
    shift
elif [ "$1 $2 $3" = 'the same day' ]; then
    shift; shift; shift
elif [ "$1" = 'the same day' ]; then
    shift
elif [ "$1 $2 $3" = 'the next day' ]; then
    shift; shift; shift
    doneDateSpan='1 day'
elif [ "$1" = 'the next day' ]; then
    shift
    doneDateSpan='1 day'
else
    [ "$1" = 'on' ] && shift
    [ "$1" ] || die "$errmsg"
    doneDate=$(date -d "$1" +%F) || exit 1
    shift
fi

# We could delegate to the built-in 'do' followed by 'replace', but the
# 'replace' command doesn't handle done tasks, and may do surprising things
# to existing priorities and dates. This also would have confusing output.
# Instead, use a hook inside my 'do' extension that overrides the built-in do.
TODOTXT_DID_DATE="$doneDate" \
TODOTXT_DID_DATESPAN="$doneDateSpan" \
TODOTXT_DO_COMMAND='did --launch' \
    "$TODO_FULL_SH" do $items "$@"
