#!/bin/bash
###############################################################################
##
# FILE:         distribution
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Feb-2022
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2022-2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)distribution	$Id$	todo.txt-cli-ex
###############################################################################

shopt -qs extglob

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [--no-footer|--final-footer-only|footer-only-on-change|--footer-every N] [--force-legends] [--bucket-legend] [--as colorbox-calendar|green-[large-]calendar|...] [--over day|month|year|year-weekly|--weekly] [--done|--both|--trashed|--any] [--all|SRC] [-d|--date DATEGLOB [-d|--date ...]] [TERM...]"
    echo "      Prints the distribution of added (or done with --done, both with --both,"
    echo "      or trashed with --trashed, any with --any) tasks"
    echo "      [in SRC, or in todo.txt and done.txt with --all (like lsa)]"
    echo "      [that match (any) DATEGLOB(s)] [that contain TERM(s)]."
    echo ""
    exit
}

filterCommand="sed -ne 's#^ *[0-9]\\+ \\((.) \\)\\?\\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\2#p'"  # get the added date of tasks not done or trashed
listAction='list'
typeset -a dateGlobs=()
typeset -a distributionArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
        --done)         shift; filterCommand="sed -ne 's#^ *[0-9]\\+ x \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\1#p'";;    # get the done date
        --trashed)      shift; filterCommand="sed -ne 's#^ *[0-9]\\+ X \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\1#p'";;    # get the trashed date
        --both)         shift; filterCommand="sed -n -e 's#^ *[0-9]\\+ \\((.) \\)\\?\\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\2#p' -e 's#^ *[0-9]\\+ x \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\1\\n\\2#p'";;   # get the added date of tasks not done or trashed, and both done and added dates of done tasks
        --any)         shift; filterCommand="sed -n -e 's#^ *[0-9]\\+ \\((.) \\)\\?\\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\2#p' -e 's#^ *[0-9]\\+ [xX] \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\1\\n\\2#p'";;   # get the added date of tasks not done or trashed, and both done / trashed and added dates of done and trashed tasks
        --all)          shift; listAction='lsa';;
        --date|-d)      shift; dateGlobs+=(-e "${1%\*}*");;    # De-anchor at the end.

        -[S])           distributionArgs+=("$1"); shift;;
        --@(no-footer|final-footer-only|footer-only-on-change|no-splitting|weekly|force-legends))
                        distributionArgs+=("$1"); shift;;
        --@(bucket-legend|footer-every|graph-legend|footer-legend|as|over))
                        distributionArgs+=("$1" "$2"); shift; shift;;

        --)             shift; break;;
        *)              break;;
    esac
done
typeset -a todoArgs=("$listAction")
if [ $# -gt 0 ]; then
    sourceFilespec="${TODO_DIR:?}/$1"
    if [ -r "$sourceFilespec" ]; then
        todoArgs=(listfile "$1")
        shift
    fi
fi

export TODOTXT_SORT_COMMAND='cat'   # Need to do sorting after todo.sh, as the "listall" action sorts each file separately.
export TODOTXT_FINAL_FILTER="$filterCommand"    # XXX: Cannot use post_filter_command; it sometimes messes up the output.
export TODOTXT_VERBOSE=0    # Omit the task number summary.

"$TODO_FULL_SH" -p "${todoArgs[@]}" "$@" | \
    eval 'sort' "${dateGlobs:+| globgrep}" '"${dateGlobs[@]}"' | \
    distribution-over-autorange "${distributionArgs[@]}"
