#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [COMMENT]"
    echo "      Marks task(s) on line ITEM# as done in todo.txt, appending COMMENT."
    echo ""
    exit
}

die()
{
    echo "$*"
    exit 1
} 

errmsg="usage: $TODO_SH do ITEM#[, ITEM#, ITEM#, ...] [COMMENT]"
[ $# -eq 0 ] && die "$errmsg"

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items="$items $1"
    shift
done
[ "$items" ] || die "$errmsg"

if [ $# -eq 0 ]; then
    # No comment was given, just pass everything to the built-in 'do' command. 
    "$TODO_FULL_SH" command do $items
else
    for item in `echo $items | tr ',' ' '`; do 
        # Call back to the main script to append the comment and mark the task
        # done. 
        "$TODO_FULL_SH" command append $item "$@" && "$TODO_FULL_SH" command do $item
    done
fi
