#!/usr/bin/env bash
###############################################################################
##
# FILE:         doagain
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 12-Nov-2021
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2021-2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)doagain	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR [NR ...] [COMMENT]"
    echo "      Marks task(s) on line(s) NR as done in todo.txt,"
    echo "      optionally appending COMMENT, and add them as open task(s) again."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] [COMMENT]"
[ $# -eq 0 ] && die "$errmsg"

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items+=" $1"; shift
done
[ "$items" ] || die "$errmsg"

"$TODO_FULL_SH" do ${items//,/ } "$@" || exit $?
for item in ${items//,/ }
do
    "$TODO_FULL_SH" addagain "$item" || exit $?
done
