#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# ITEM#[, ITEM#, ...]"
    echo "      Link the tasks on lines ITEM# together as duplicate tasks."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM# ITEM#[, ITEM#, ...]"

[ $# -lt 2 ] && die "$errmsg"

# Split multiple duplicates, if comma separated change to whitespace separated. 
items=$(echo $* | tr ',' ' ')

for item in $items; do 
    "$TODO_FULL_SH" link $item "${items/$item/}"
done
