#!/usr/bin/env bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

TODOTXT_GDELFILE_PROJECTS_SIGIL='@' \
TODOTXT_GDELFILE_PROJECTS_WHAT='@contexts' \
    exec "${scriptDir}/gdelfileprojects" "$@"
