#!/usr/bin/env bash
###############################################################################
##
# FILE:         gedit
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 10-May-2018
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# SOURCE:
#
# COPYRIGHT: (C) 2010-2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)gedit	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [NR] [SRC]"
    echo "      Open task on line NR in \$TODO_DIR/SRC in \$GUI_EDITOR for editing in a"
    echo "      GUI editor."
    echo "      If NR is omitted, the entire file is edited."
    echo "      If BASENAME is not given, defaults to 'todo'."
    echo "      The task on line NR can be removed by deleting the line."
    echo "      Additional tasks can be added by appending more lines."
    echo ""
    exit
}

[ "$GUI_EDITOR" ] && EDITOR=$GUI_EDITOR
export EDITOR
exec "$TODO_FULL_SH" edit "$@"
