#!/usr/bin/env bash
###############################################################################
##
# FILE:         gsub
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 20-May-2010
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)gsub	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR [NR ...] PATTERN REPLACEMENT [PATTERN REPLACEMENT ...]"
    echo "      Replaces all instances of (sed-style) PATTERN with REPLACEMENT"
    echo "      on line(s) NR."
    echo ""
    exit
}

shopt -s extglob
errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] PATTERN REPLACEMENT [PATTERN REPLACEMENT ...]"
items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items+=" $1"; shift
done

replace()
{
    local pattern="${1:?}"; shift
    local input="${1?}"; shift
    cleaninput
    input=${input//%/\\%}
    # Above takes care of the replacement; for the pattern, we only have to escape
    # the substitution delimiter, as it's supposed to be an sed regexp.
    # Note: Use a substitution delimiter that has no special meaning as a regexp
    # symbol. For example, "|" causes problems when it is contained in pattern
    # (e.g. /\(^\| \)/), and then mistakenly double-escaped.
    newtodo=$(echo "$newtodo" | sed "s%${pattern//%/\\%}%${input}%g") || exit 1
}

typeset -a patterns=()
typeset -a replacements=()
if [ $# -lt 2 ]; then
    [ $TODOTXT_FORCE = 0 ] || die "$errmsg"
    readinput 'Pattern' || exit 1
    patterns+=("$input")
    readinput 'Replacement'
    replacements+=("$input")
else
    while [[ $# -ge 2 ]]
    do
        patterns+=("$1")
        replacements+=("$2")
        shift; shift
    done
fi

didReplace=
typeset -a tasksWithoutReplacements=()
for item in ${items//,/ }
do
    getTodo "$item"
    # Get task without potential priority, the "replace" command will maintain the
    # priority.
    todo=${todo#(?) }
    newtodo=$todo

    for ((i = 0; i < ${#patterns[@]}; i++))
    do
        replace "${patterns[$i]}" "${replacements[$i]}"
    done

    [ -n "$newtodo" ] || die "TODO: Replacement would create empty task: $item $todo"
    if [ "$newtodo" = "$todo" ]; then
        tasksWithoutReplacements+=("$item $todo")
    else
        didReplace=t
        "$TODO_FULL_SH" command replace $item "$newtodo"
    fi
done
if [ ! "$didReplace" ]; then
    [ $TODOTXT_VERBOSE -gt 0 ] && printf '%s\n' "${tasksWithoutReplacements[@]}"
    IFS=,; die "TODO: No replacement done for ${patterns[*]}"
fi
