#!/bin/bash
###############################################################################
##
# FILE:         here
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 01-Feb-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)here	001	(24-Feb-2012)	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [DATE] [TERM...]"
    echo "      Displays all tasks with a context of the current host / location."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

[ "$HOSTNAME" ] || die "Cannot determine hostname!"

post_filter_command="grep -ve '^ *[0-9]\+ [xX] ' | grep -e '@$(echo "$HOSTNAME" | tr 'A-Z' 'a-z')'"
_list "$TODO_FILE" "$@"
