#!/bin/bash
###############################################################################
##
# FILE:         here
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 01-Feb-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)here	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-s] [TERM...]"
    echo "      Displays all tasks with a context of the current host / location."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo "      With -s, show just the summary."
    echo ""
    exit
}

isSummaryOnly=
if [ "$1" = '-s' ]; then
    isSummaryOnly=t
    shift
fi

[ "$HOSTNAME" ] || die "TODO: Cannot determine hostname!"

post_filter_command="grep -ve '^ *[0-9]\+ [xX] ' | grep -e '@$(echo "$HOSTNAME" | tr 'A-Z' 'a-z')'"
if [ "$isSummaryOnly" ]; then
    cnt=$(TODOTXT_VERBOSE=0 _list "$TODO_FILE" "$@" | wc -l)
    if [ $cnt -ge 1 ]; then
        printf 'TODO: You have %d local task(s) open on this system.\n' $cnt
    fi
else
    _list "$TODO_FILE" "$@"
fi
