#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays the last few tasks sorted by priority with line numbers."
    echo ""
    exit
}

TODOTXT_SORT_COMMAND="tail -n 10 | $TODOTXT_SORT_COMMAND"
TODOTXT_FILTER_FUTURE_TASKS=0

_list "$TODO_FILE" "$@"
