#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-a] [TERM...]"
    echo "    lt [TERM...]"
    echo "      Displays the last added open (all with -a) tasks"
    echo "      that contain TERM(s). Tasks without a date are ignored."
    echo ""
    exit
}

export TODOTXT_LST_ADDITIONAL_SORT_COMMAND='tail -n 10'
exec "$TODO_FULL_SH" listbydate "$@"
