#!/usr/bin/env bash
###############################################################################
##
# FILE:         latest
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 06-Jan-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)latest	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-n NUM] [-a] [TERM...]"
    echo "    lt [TERM...]"
    echo "      Displays the last [NUM] added open (all with -a) tasks"
    echo "      that contain TERM(s). Tasks without a date are ignored."
    echo ""
    exit
}

additional_filter_command="grep -ve '^ *[0-9]\+ [xX] ' | "
typeset -a listByDateArgs=()
if [ "$1" = '-a' ]; then
    listByDateArgs+=("$1"); shift
    additional_filter_command=
fi

summaryNum=$((${LINES:-20}/2 - 4))
if [ "$1" = '-n' ]; then
    summaryNum=$2; shift; shift
fi

export TODOTXT_LST_ADDITIONAL_SORT_COMMAND="tail -n $summaryNum"
exec "$TODO_FULL_SH" listbydate "${listByDateArgs[@]}" "$@"
