#!/usr/bin/env bash
###############################################################################
##
# FILE:         lifetimes
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 28-Nov-2024
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2024 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lifetimes	$Id$	todo.txt-cli-ex
###############################################################################

shopt -qs extglob

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [--both|--trashed] [--all|SRC] [-d|--date DATEGLOB [-d|--date ...]] [TERM...]"
    echo "      Prints statistics about the number of days that done (or trashed with"
    echo "      --trashed, or both with --both) tasks were active"
    echo "      [in SRC, or in todo.txt and done.txt and trash.txt with --all (like lsa)]"
    echo "      [that match (any) DATEGLOB(s)] [that contain TERM(s)]."
    statistics --legend-only | prefix $'\t'
    echo ""
    exit
}

typeFilter='x'
listAction='list'
typeset -a dateGlobs=()
while [ $# -ne 0 ]
do
    case "$1" in
        --trashed)      shift; typeFilter='X';;
        --both)         shift; typeFilter='[xX]';;
        --all)          shift; listAction='lsa';;
        --date|-d)      shift; dateGlobs+=(-e "${1%\*}*");;    # De-anchor at the end.

        --)             shift; break;;
        *)              break;;
    esac
done
typeset -a todoArgs=("$listAction")
if [ $# -gt 0 ]; then
    sourceFilespec="${TODO_DIR:?}/$1"
    if [ -r "$sourceFilespec" ]; then
        todoArgs=(listfile "$1")
        shift
    fi
fi

toLifetime()
{
    awk --field-separator $'\t' \
'
function toEpoch(timestamp)
{
    return mktime(gensub("-", " ", "g", timestamp) " 12 00 00", 1)
}
function abs(v)
{
    v += 0
    return (v < 0 ? -v : v)
}
{
    endEpoch = toEpoch($1)
    startEpoch = toEpoch($2)
    if (startEpoch != -1 && endEpoch != -1) {
        print(abs(endEpoch - startEpoch) / 86400)
    }
}
'
}

export TODOTXT_SORT_COMMAND='cat'   # Need to do sorting after todo.sh, as the "listall" action sorts each file separately.
export TODOTXT_FINAL_FILTER="sed -n -e 's#^ *[0-9]\\+ $typeFilter \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) \\([0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\) .*\$#\\1\\t\\2#p'"
export TODOTXT_VERBOSE=0    # Omit the task number summary.

eval '"$TODO_FULL_SH" -p "${todoArgs[@]}" "$@"' \
    "${dateGlobs:+| globgrep}" '"${dateGlobs[@]}"' \
    | toLifetime \
    | STATISTICS_PRECISION=0 statistics \
    | secondsToDuration --factor 86400 --precision 8 --skip '[N≠]:&'
