#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Lists all the wait reasons (w:... markers) in active tasks."
    echo "      If TERM specified, considers only tasks that contain TERM."
    echo ""
    exit
}

eval "$(filtercommand 'cat "$TODO_FILE"' '' "$@")" | sed -e '/^x /d' -e '/ w:/!d' -e 's/ w:[^ ]/\n&/g' | sed -n -e 's/^.* w:(\([^)]*\)).*$/\1/p;t' -e 's/^.* w:\([^ 0-9]*\)$/\1/p' | sort -u
