#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all tasks that aren't done yet and contain TERM(s)"
    echo "      sorted by priority with line numbers."
    echo "    $(basename $0) ITEM#"
    echo "      Displays task ITEM#."
    echo ""
    exit
}

shopt -s extglob

# Consider only tasks that are not yet done. The tasks are already numbered when
# the filter is applied, so there definitely is a space in front of the marker. 
post_filter_command="grep -ve '^ *[0-9]\+ x '"

if [[ $# -eq 1 && "$1" = +([0-9]) ]]; then
    # Listing of task numbers is unintuitive, because the search pattern is
    # applied in the middle of alignment, when the numbers have already been
    # space- (but not zero-) aligned. 
    _list "$TODO_FILE" "^ *${1##*(0)} "
    exit
fi

_list "$TODO_FILE" "$@"
