#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    $(basename $0) [TERM...]"
  echo "      Displays all done, but not yet archived tasks from todo.txt."
  echo "      If TERM specified, lists only tasks that contain TERM."
  echo ""
  exit
}

_list "$TODO_FILE" "^ *[0-9]\+ x " "$@"
