#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all done (as well as archived) tasks."
    echo "      If TERM specified, lists only tasks that contain TERM."
    echo ""
    exit
}

# Omit the "done" highlighting in favor of the more readable alternating task
# highlighting for readability; all tasks are done, anyway. 
export HIDE_COLOR_DONE=1

# Note: Cannot use the usual post_filter_command; listall uses that itself. 
# (And I use pre_filter_command myself.) 
"$TODO_FULL_SH" command listall '^ *[0-9]\+ x ' "$@"
