#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    $(basename $0) [PRIORITY] [TERM...]"
  echo "      Displays all tasks prioritized PRIORITY (or all prioritized tasks)."
  echo "      If TERM specified, lists only tasks that contain TERM."
  echo ""
  exit
}

pri=$( printf "%s\n" "$1" | tr 'a-z' 'A-Z' | grep '^[A-Z]$' ) && shift || pri="[[:upper:]]"
post_filter_command="grep -e '^ *[0-9]\+ (${pri})'"
_list "$TODO_FILE" "$@"
