#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    $(basename $0) [PRIORITY] [TERM...]"
  echo "      Displays all items prioritized PRIORITY (or all prioritized items)."
  echo "      If TERM specified, lists only lines that contain TERM."
  echo ""
  exit
}

pri=$( printf "%s\n" "$1" | tr 'a-z' 'A-Z' | grep '^[A-Z]$' ) && shift || pri="[[:upper:]]"
pri="($pri)"
_list "$TODO_FILE" "$pri" "$@"
