#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all trashed tasks from todo.txt and trash.txt."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

"$TODO_FULL_SH" lstrashable "$@"
echo ""
"$TODO_FULL_SH" lstrash "$@"
