#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all trashed tasks from todo.txt and trash.txt."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

# Omit the "trashed" highlighting in favor of the more readable alternating task
# highlighting for readability; all tasks are trashed, anyway. 
# This only works for "todo.sh ls", but we invoke _list() directly.  
#export HIDE_COLOR_TRASH=1
unset COLOR_TRASH

post_filter_command="grep -e '^ *[0-9]\+ X '"
_list "$TODO_FILE" "$@"
echo ""
exec "$TODO_FULL_SH" lstrash "$@"
