#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all blocked tasks that wait for a precondition."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

# Consider only tasks that are not yet done or trashed and contain the "w:" wait
# marker.
# The tasks are already numbered when the filter is applied, so there definitely
# is a space in front of the marker. 
post_filter_command="grep -ve '^ *[0-9]\+ [xX] ' | grep -e ' w:[^ ]'"

_list "$TODO_FILE" "$@" | sed -e "/^TODO:/s/of [0-9]\+ tasks shown/blocked \0/"
