#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-t] [-e | -m MESSAGE] TERM..."
    echo "      Sends all tasks that aren't done yet and contain TERM(s),"
    echo "      putting the tasks into the email body."
    echo "    $(basename $0) [-t] [-e | -m MESSAGE] [-s] ITEM#"
    echo "      Sends task ITEM#, using the task for the email subject."
    echo "      -t just prints what would be sent."
    echo "      -s puts task ITEM# directly into the subject."
    echo "      -e edits the email body before sending."
    echo "      -m uses MESSAGE as the email body."
    echo "      Recipients are taken from @Person (first letter uppercase, must be found"
    echo "      in email address book then), @name@host, or if none is found uses"
    echo "      TODOTXT_MAIL_DEFAULT_RECIPIENTS"
    echo "	The email can be copied to TODOTXT_MAIL_DEFAULT_CC and"
    echo "	TODOTXT_MAIL_DEFAULT_BCC."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) [-t] [-e | -m MESSAGE] TERM... | [-s] ITEM#"

shopt -s extglob

type -P email >/dev/null || die "TODO: Cannot send email; command 'email' not found!"

# Consider only tasks that are not yet done. The tasks are already numbered when
# the filter is applied, so there definitely is a space in front of the marker. 
post_filter_command="grep -ve '^ *[0-9]\+ x '"

# No highlighting and verbose summary. 
TODOTXT_VERBOSE=0
TODOTXT_PLAIN=1


cc=$TODOTXT_MAIL_DEFAULT_CC
bcc=$TODOTXT_MAIL_DEFAULT_BCC
taskInSubject=
isTest=
isEdit=
singleTask=
message=
noTasksError='No tasks found.'
while getopts ":s:tem:" opt; do
    case "$opt" in
	's') taskInSubject=$OPTARG;;
	't') isTest='true';;
	'e') isEdit='true';;
	'm') message=$OPTARG;;
    esac
done
shift $(( $OPTIND - 1 ))

if [[ "$taskInSubject" = +([0-9]) ]]; then
    singleTask=$taskInSubject
    noTasksError="No task $taskInSubject."
    # Listing of task numbers is unintuitive, because the search pattern is
    # applied in the middle of alignment, when the numbers have already been
    # space- (but not zero-) aligned. 
    set -- "^ *${taskInSubject##*(0)} "
elif [[ $# -eq 1 && "$1" = +([0-9]) ]]; then
    singleTask=$1
    noTasksError="No task $1."
    # Listing of task numbers is unintuitive, because the search pattern is
    # applied in the middle of alignment, when the numbers have already been
    # space- (but not zero-) aligned. 
    set -- "^ *${1##*(0)} "
fi

tasks=$(_list "$TODO_FILE" "$@")
[ "$tasks" ] || die "TODO: $noTasksError"

recipients=$(echo "$tasks" | grep -o '[^ ]*@[^ ]\+' | sed -ne '/^@\([[:upper:]]\|.\+@.\+\)/s/^.//p' | sort -u)
[ "$recipients" ] || recipients=$TODOTXT_MAIL_DEFAULT_RECIPIENTS
if [ ! "$recipients" ]; then
    echo "$tasks"
    die 'TODO: No recipients found.'
fi

if [ "$taskInSubject" ]; then
    subject=$tasks
    body=
else
    if [ "$singleTask" ]; then
	subject="Task $singleTask"
    else
	subject="Tasks $*"
    fi
    body=$tasks
fi
if [ "$message" ]; then
    if [ "$body" ]; then
	body="$message
$body"
    else
	body=$message
    fi
fi

printEmail()
{
    [ "$1" ] && local bodySeparator="-=-=-=-=-=-=-=-=-=# Don't remove this line #=-=-=-=-=-=-=-=-=-
" || local bodySeparator=
    cat <<EOF
Subject:   $subject
To:        $recipients
Cc:        $cc
Bcc:       $bcc
${bodySeparator}${body}
EOF
}

if [ "$isEdit" ]; then
    cleanup()
    {
	rm "$TMPEDIT" 2>/dev/null
    }
    trap 'cleanup' EXIT
    TMPEDIT=$(mktemp --tmpdir "todo-mail-XXXXXX.eml" 2>/dev/null || echo "${TEMP:-/tmp}/todo-mail-$$.eml")
    printEmail true > "$TMPEDIT"
    "$EDITOR" "$TMPEDIT" || { echo 2>&1 "Unclean exit of editor; aborting!"; exit $?; }
    subject=$(sed -ne '/^Subject:/{ s/^[^ ]\+: *\(.*\)$/\1/p; q }' "$TMPEDIT")
    recipients=$(sed -ne '/^To:/{ s/^[^ ]\+: *\(.*\)$/\1/p; q }' "$TMPEDIT")
    cc=$(sed -ne '/^Cc:/{ s/^[^ ]\+: *\(.*\)$/\1/p; q }' "$TMPEDIT")
    bcc=$(sed -ne '/^Bcc:/{ s/^[^ ]\+: *\(.*\)$/\1/p; q }' "$TMPEDIT")
    body=$(sed -e "1,/^-=-=-=-=-=-=-=-=-=# Don't remove this line #=-=-=-=-=-=-=-=-=-$/d" "$TMPEDIT")
fi

if [ "$isTest" ]; then
    printEmail
    exit 0
fi

[ "$recipients" ] || die "TODO: No recipients specified!"
echo "$body" | eval 'email --subject "$subject"' ${cc:+--cc '"$cc"'} ${bcc:+--bcc '"$bcc"'} '"$recipients"'
