#!/usr/bin/env bash
###############################################################################
##
# FILE:         mvreference
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 11-Jul-2026
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)mvreference	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0)"
    echo "      Change cross-task references of the form m:### or \"task ###\" from OLDNR"
    echo "      to NEWNR."
    echo ""
    exit
}

set -o pipefail
shopt -qs extglob

: ${TODOTXT_TASK_MARKER_PATTERN:='^[[:graph:]]:[0-9]+$'}
: ${TODOTXT_TASK_REFERENCE_PATTERN:='^task$'}

errmsg="usage: $TODO_SH $(basename $0) OLDNR NEWNR"

[ $# -eq 2 ] || die "$errmsg"
[[ "$1" = +([0-9]) && "$2" = +([0-9]) ]] || die "$errmsg"
oldItem=$1; shift
newItem=$1; shift

awk \
        -v "markerPattern=$TODOTXT_TASK_MARKER_PATTERN" \
        -v "referencePattern=$TODOTXT_TASK_REFERENCE_PATTERN" \
        -v "oldItem=$oldItem" \
        -v "newItem=$newItem" \
'
BEGIN { FS = "[ \t]" }
{
    for (i = 1; i <= NF; ++i) {
        if ($i ~ markerPattern) {
            match($i, /[0-9]+/)
            oldNum = substr($i, RSTART, RLENGTH) + 0
            if (oldNum == oldItem) {
                sub(/[0-9]+/, newItem, $i)
            }
        } else if ($(i - 1) ~ referencePattern && $i ~ /^[0-9]+$/) {
            oldNum = $i + 0
            if (oldNum == oldItem) {
                $i = newItem
            }
        }
    }
}; 1' \
    "$TODO_FILE" > "${TODO_FILE}.bak" \
        && mv "${TODO_FILE}.bak" "${TODO_FILE}" \
        || die 'Fatal Error: Unable to process tasks.'
