#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ...]"
    echo "      Searches for URLs in the task text and launches a browser."
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all tasks that contain URLs and TERM(s)."
    echo ""
    exit
}

if [[ ! "$1" =~ ^[0-9]+$ ]]; then
    post_filter_command="grep '[a-z]\\+://[^ ]\\+'"
    _list "$TODO_FILE" "$@"
    exit 0
fi

typeset -a urls=()
while [ $# -gt 0 ]
do
    item=$1
    shift
    getTodo "$item"

    taskUrls=$(echo "$todo" | grep -o '[a-z]\+://[^ ]\+')
    if [ -z "$taskUrls" ]; then
        [ $TODOTXT_VERBOSE -gt 0 ] && echo "$item $todo"
        echo "TODO: No URL found in task $item."
    fi

    for url in $taskUrls
    do
        urls+=("$url")
        echo "adding $url"
    done
done
[ ${#urls} -gt 0 ] || exit 1



# Trying to be smart...
# on Debian alike:
if [ "$TODOTXT_BROWSER" ]; then
    exec "$TODOTXT_BROWSER" "${urls[@]}"
elif $(which x-www-browser >/dev/null 2>&1); then
    exec x-www-browser "${urls[@]}"
# with freedesktop.org utils:
elif $(which xdg-open >/dev/null 2>&1); then
    exec xdg-open "${urls[@]}"
# if you have git:
elif [ -x /usr/lib/git-core/git-web--browse ]; then
    cd /usr/lib/git-core && ./git-web--browse "${urls[@]}"
# last resort, a la mano...
elif $(which firefox >/dev/null 2>&1); then
    exec firefox "${urls[@]}"
elif $(which konqueror >/dev/null 2>&1); then
    exec konqueror "${urls[@]}"
elif $(which nautilus >/dev/null 2>&1); then
    exec nautilus "${urls[@]}"
# Windows?
elif [ -x "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" ]; then
    exec "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" "${urls[@]}"
elif [ -x "/cygdrive/c/Program Files (x86)/Mozilla Firefox/firefox.exe" ]; then
    exec "/cygdrive/c/Program Files (x86)/Mozilla Firefox/firefox.exe" "${urls[@]}"
# OS X?
elif [ -x "/usr/bin/open" ]; then
    exec "/usr/bin/open" "${urls[@]}"
else
    echo "Sorry I'm giving up, cannot find your browser :-("
    echo "Under cygwin, consider creating a shortcut in the path, like"
    echo "ln -s \"/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe\" /usr/local/bin/firefox"

    exit 1
fi
