#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) PRIORITY ITEM#[, ITEM#, ITEM#, ...]"
    echo "    $(basename $0) ITEM# PRIORITY"
    echo "      Adds PRIORITY to task(s) on line ITEM#."
    echo ""
    exit
}

errmsg="usage: $TODO_SH pri PRIORITY ITEM#[, ITEM#, ITEM#, ...]"
if [[ "$1" = [a-zA-Z] ]]; then
    pri=$1
    shift
elif [[ $# -eq 2 && "$2" = [a-zA-Z] ]]; then
    pri=$2
    set -- "$1"
else
    die "$errmsg"
fi
[ $# -eq 0 ] && die "$errmsg"

for item in `echo $* | tr ',' ' '`; do 
    # Call back to the main script to prioritize each item. 
    "$TODO_FULL_SH" command pri $item $pri
done
