#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) PRIORITY [on DATE|DATE-] [until DATE|-DATE] ITEM#[, ITEM#, ITEM#, ...]"
    echo "    $(basename $0) ITEM# PRIORITY [on DATE|DATE-] [until DATE|-DATE]"
    echo "      Adds PRIORITY to task(s) on line ITEM#."
    echo "	With on DATE or DATE-, priorization will only happen on DATE (via A:DATE)."
    echo "	With until DATE or -DATE, the task will be deprioritized on DATE (via d:DATE)."
    echo ""
    exit
}

shopt -s extglob

errmsg="usage: $TODO_SH $(basename $0) PRIORITY [on DATE|DATE-] [until DATE|-DATE] ITEM#[, ITEM#, ITEM#, ...]"
beginDate=
endDate=
makeDate()
{
    date -d "$1" +%F
}
checkDates()
{
    while [ $# -gt 0 ]
    do
	case "$1" in
	    on)	    beginDate=$(makeDate "$2") || exit 1; shift; shift;;
	    [^-]*-) beginDate=$(makeDate "${1%-}") || exit 1; shift;;
	    until)  endDate=$(makeDate "$2") || exit 1; shift; shift;;
	    -*[^-]) endDate=$(makeDate "${1#-}") || exit 1; shift;;
	    *)	    break;;
	esac
    done
    items=$*
}
datePri()
{
    local marker=$1
    local date=$2

    todo=$(sed -e "$item!d" "$TODO_FILE")
    [ -z "$todo" ] && die "TODO: No task $item."
    # Replace existing date-priorization with the same priority in-place or
    # append new date-priorization. Remove any other (de-)priorizations for the
    # same date. 
    newTodo=$(echo "$todo" | sed -e "s| [dA-Z]:$date||" | sed -e "s| $marker:\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}| ${marker}:${date}|" -e t -e "s| *\$| ${marker}:${date}|") || exit 1
    local -r escapedNewTodo=$(echo "$newTodo" | sed 's/\&/\\\&/g')
    sed -i.bak "$item s|^.*|${escapedNewTodo}|" "$TODO_FILE"
}

if [[ "$1" = [a-zA-Z] ]]; then
    pri=$1
    shift
    checkDates "$@"
elif [[ $# -ge 2 && "$2" = [a-zA-Z] ]]; then
    item=$1
    shift
    pri=$1
    shift
    checkDates "$@"
    items=$item
else
    die "$errmsg"
fi
[ $# -eq 0 ] && die "$errmsg"
newpri=$( printf "%s\n" "$pri" | tr 'a-z' 'A-Z' )

for item in $(echo $items | tr ',' ' '); do 
    whenwhat=
    [ -z "$item" ] && die "$errmsg"
    [[ "$item" = +([0-9]) ]] || die "$errmsg"

    if [ "$beginDate" ]; then
	whenwhat="will be prioritized ($newpri) on $beginDate"
	datePri "$newpri" "$beginDate"

	if [ "$endDate" ]; then
	    whenwhat="${whenwhat}, until $endDate"
	    datePri "d" "$endDate"
	fi
    else
	# Call back to the main script to prioritize each task. 
	if [ "$endDate" ]; then
	    TODOTXT_VERBOSE=0 "$TODO_FULL_SH" command pri $item $newpri
	    whenwhat="prioritized ($newpri) until $endDate"
	    datePri "d" "$endDate"
	else
	    "$TODO_FULL_SH" command pri $item $newpri
	fi
    fi
    
    if [ "$whenwhat" -a $TODOTXT_VERBOSE -gt 0 ]; then
	echo "$item $newTodo"
	echo "TODO: $item $whenwhat."
    fi
done
