#!/bin/bash
# 2009 Paul Mansfield
# License:  GPL, http://www.gnu.org/copyleft/gpl.html

action=$1
shift

if [ "$action" = "usage" ]; then
    echo "    $(basename $0) [TERM...]"
    echo "      Show tasks containing TERM, grouped by project, and displayed in"
    echo "      priority order. If no TERM provided, displays entire todo.txt."
    echo ""
    exit
fi

# Stop Verbose lines, thanks to Mark Harrison
original_TODOTXT_VERBOSE=$TODOTXT_VERBOSE
TODOTXT_VERBOSE=0

# Show projects in alphabetical order and tasks in priority order. 
let PROJECT_CNT=0
TASKS=

# Find all projects and sort. 
PROJECTS=$(grep -o '[^ ]*+[^ ]\+' "$TODO_FILE" | grep '^+' | sort -u | sed 's/^+//g')
# For each project show header and the list of tasks. 
for i in $PROJECTS; do 
    # Use core _list function, does numbering and coloring for us. 
    PROJECT_LIST=$(_list "$TODO_FILE" "+$i\( \|$\)" "$@")
    if [[ -n "${PROJECT_LIST}" ]]; then
        echo "--- $i ---"
        echo "${PROJECT_LIST}" | sed 's/\( *+[^ ]\+\)\+ */ /g'
        echo ""

        if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
            let PROJECT_CNT+=1
            TASKS="${TASKS}${TASKS:+
}$PROJECT_LIST"
        fi
    fi
done

# Show tasks not associated to a project. 
PROJECT_LIST=$(_list "$TODO_FILE" "$@" | grep -v " \++[^ ]")
if [[ -n "${PROJECT_LIST}" ]]; then
    echo "--- Not in projects ---"
    echo "${PROJECT_LIST}"
fi

if [ "$original_TODOTXT_VERBOSE" -gt 0 ]; then
    let TASK_CNT=$(echo "$TASKS" | sort -u | sed -n '$ =')

    echo "--"
    if [ $PROJECT_CNT -gt 0 ]; then
        echo "TODO: $TASK_CNT task(s) in $PROJECT_CNT projects."
    else
        echo "TODO: No projects found."
    fi
fi
