#!/bin/bash

[ "$1" = "usage" ] && exit

readonly scriptDir=$(readonly scriptFile="$(type -P -- "$0")" && dirname -- "$scriptFile" || exit 2)
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }

exec "$scriptDir/projectview" "$@"
