#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# RELATIVEDATE"
    echo "      Make task ITEM# recurrent each RELATIVEDATE."
    echo "    $(basename $0) ITEM# none|never"
    echo "      Remove the recurrent scheduling of task ITEM#."
    echo ""
    exit
}

shopt -s extglob
errmsg="usage: $TODO_SH $(basename $0) ITEM# RELATIVEDATE|none|never"
item=$1; shift

[ -z "$item" ] && die "$errmsg"
[[ "$item" = +([0-9]) ]] || die "$errmsg"
# Get task without potential priority. 
todo=$(sed -e "$item!d" -e "s/^(.) //" "$TODO_FILE")
[ -z "$todo" ] && die "TODO: No task $item."

recur=$*; shift
isRemove=
if [ "$recur" = "none" -o "$recur" = "never" ]; then
    isRemove='true'
    newtodo=$(echo "$todo" | sed 's#[[:space:]]\+{[^}]\+}\([[:space:]]\|$\)#\1#')
else
    nextdate=$(date -d "$recur" +%F) || exit 1
    recurrence="{${recur}} t:${nextdate}"
    newtodo=$(echo "$todo" | sed -e 's#[[:space:]]\+t:\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}##g' -e '/[[:space:]]\+{[^}]\+}[[:space:]]\|$/{ s#\([[:space:]]\+\){[^}]\+}\([[:space:]]\|$\)#\1'"${recurrence}"'\2#;b }' -e 's#$# '"${recurrence}"'#')
fi
if [ "$newtodo" = "$todo" ]; then
    [ $TODOTXT_VERBOSE -gt 0 ] && echo "$item: $todo"
    die "TODO: Recurrence didn't change"
fi
"$TODO_FULL_SH" command replace $item "$newtodo"
if [ ! "$isRemove" ]; then
    nowSeconds=$(date +%s)
    nextSeconds=$(date -d "$recur" +%s)
    echo "TODO: Next scheduled for $nextdate, in $(((nextSeconds - nowSeconds) / (24 * 3600))) day(s)"
fi
