#!/bin/bash

action=$1
shift
item=$1
shift
param="$*"

shopt -s extglob
pattern=" t:\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}" # not enforcing any particular format
syntax="$(basename $0) [ITEM# DATE|(none|never|off|del|rm) | del ITEM# | rm ITEM#]"
errmsg="usage: $TODO_SH $syntax"

usage()
{
	echo "    $syntax"
	echo "      Set, change or remove date threshold of a task."
	echo "      If arguments are omitted, all scheduled tasks are listed."
	echo "      Intended to be used with futureTasks "
	echo "      (http://github.com/FND/todo.txt-cli/blob/extensions/futureTasks)."
	echo "      Example: $ $TODO_SH $(basename $0) 42 tomorrow"
	echo ""
	exit
}

list()
{
	# Ensure that a futureTasks filter is not set. 
	if [[ "$TODOTXT_FINAL_FILTER" == *utureTasks* ]]; then
		TODOTXT_FINAL_FILTER="|${TODOTXT_FINAL_FILTER}|"
		TODOTXT_FINAL_FILTER="${TODOTXT_FINAL_FILTER/|+([^|])utureTasks+([^|])|/}"
		TODOTXT_FINAL_FILTER="${TODOTXT_FINAL_FILTER#|}"
		TODOTXT_FINAL_FILTER="${TODOTXT_FINAL_FILTER%|}"
	fi
	post_filter_command="sed -e '/^ *[0-9]\+ x /d' -e '/$pattern/!d'"
	_list "$TODO_FILE"
}

getTask()
{
	item=$1
	# Remove threshold, item number and priority. 
	sed	-e "$item!d" \
		-e "s/$pattern//" \
		-e "s/^[0-9]* //" \
		-e "s/^([A-Z])* //" \
		"$TODO_FILE"
}

remove()
{
	item=$1
	[ -z "$item" ] && die "$errmsg"
	[[ "$item" = +([0-9]) ]] || die "$errmsg"

	task=$(getTask "$item")
	"$TODO_FULL_SH" command replace $item "$task" # N.B.: retains priority
}

replace()
{
	item=$1
	threshold=$2
	[ -z "$item" ] && die "$errmsg"
	[[ "$item" = +([0-9]) ]] || die "$errmsg"
	[ -z "$threshold" ] && die "$errmsg"

	task=$(getTask "$item")
	date=$(date -d "$threshold" +%F) || return 1
	"$TODO_FULL_SH" command replace $item "$task t:$date"
}

[ "$action" = 'usage' ] && usage

if [ -z $item ]; then
	list
elif [ "$param" = 'del' -o "$param" = 'rm' -o "$param" = 'none' -o "$param" = 'never' -o "$param" = 'off' ]; then
	remove $item
elif [ "$item" = 'del' -o "$item" = 'rm' ]; then
	# Allow reverse syntax: todo.sh schedule ITEM# del, too.  
	remove $param
else
	replace $item "$param"
fi
