#!/usr/bin/env bash
###############################################################################
##
# FILE:         splitopenparts
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 25-Nov-2013
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2013-2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)splitopenparts	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR"
    echo "      Creates a new task with all parts of line NR that are not yet marked"
    echo "      as partially done, and marks the original task as done."
    echo ""
    exit
}

: ${TODOTXT_COMMENT_SYMBOL:= => }
: ${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN=',? +and +|[,;] +'}   # Note: This is in Extended regular expression format (ERE).
: ${TODOTXT_PARTIALDONE_PATTERN="\\([^()]+${TODOTXT_COMMENT_SYMBOL}[0-9]{4}-[0-9]{2}-[0-9]{2}( [^()]+)?\\)"}   # Note: This is in Extended regular expression format (ERE).
shopt -s extglob
readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
readonly projectDir="${scriptDir}/.."
readonly libDir="${projectDir}/lib"
source "${libDir}/common.sh" || exit 3

errmsg="usage: $TODO_SH $(basename $0) NR"
item=$1; shift
[ -z "$item" ] && die "$errmsg"
[[ "$item" = +([0-9]) ]] || die "$errmsg"
getTodo "$item"

splitTodo "$todo"
openParts=$(echo "$text" | sed -E -e "s/${TODOTXT_PARTIALDONE_PATTERN}//g" -e "s/(${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN})+/\1/g" -e "s/^ *${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN}//" -e "s/${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN} *$//")
[ "$openParts" ] || die "TODO: No open parts found."

doneParts=$(echo "$text" | sed -E -e "s/${TODOTXT_PARTIALDONE_PATTERN}(${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN})?/\n&\n/g" | grep -E "${TODOTXT_PARTIALDONE_PATTERN}" | tr -d "\n" | sed -E -e "s/${TODOTXT_PARTIALDONE_SEPARATOR_PATTERN}$//")
[ "$doneParts" ] || die "TODO: No partially done parts found."


# The 'replace' command doesn't handle done tasks, and may do surprising things
# to existing priorities and dates. To avoid surprises, do the complete
# replacement of the line here.
input="${priAndAddDate}${prepends}${doneParts}${appends}"
cleaninput "for sed"
sed -i.bak "$item s|^.*|${input}|" "$TODO_FILE" || exit $?
if [ $TODOTXT_VERBOSE -gt 0 ]; then
    echo "$item $todo"
    echo "TODO: Replaced task with partially done parts:"
fi
"$TODO_FULL_SH" do $item
"$TODO_FULL_SH" -T add "${priAndAddDate}${prepends}${openParts}${appends}"
