#!/usr/bin/env bash
###############################################################################
##
# FILE:         stop
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)stop	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) NR [NR ...]|all [on DATE|DATE-] [COMMENT]"
    echo "    $(basename $0) [on DATE|DATE-] NR [NR ...]|all [COMMENT]"
    echo "      Marks task(s) on line NR as not being worked on any more in todo.txt,"
    echo "      optionally appending COMMENT."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] [on DATE|DATE-] [COMMENT]"
[ $# -eq 0 ] && die "$errmsg"

"$TODO_FULL_SH" depri "$@"
