#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    $(basename $0) ITEM# PATTERN REPLACEMENT"
  echo "      Replaces PATTERN with REPLACEMENT on line ITEM#."
  echo ""
  exit
}

die()
{
    echo "$*"
    exit 1
}

shopt -s extglob
errmsg="usage: $TODO_SH $(basename $0) ITEM# PATTERN REPLACEMENT"
item=$1; shift

[ -z "$item" ] && die "$errmsg"
[[ "$item" = +([0-9]) ]] || die "$errmsg"
# Get item without potential priority. 
todo=$(sed -e "$item!d" -e "s/^(.) //" "$TODO_FILE")
[ -z "$todo" ] && die "$item: No such task."

if [[ $# -ne 2 && $TODOTXT_FORCE = 0 ]]; then
    echo -n "Pattern: "
    read pattern
    echo -n "Replacement: "
    read replacement
else
    pattern=$1
    replacement=$2
fi
newtodo=$(echo "$todo"|sed "s|$pattern|$replacement|g")
[ "$todo" = "$newtodo" ] && die "No replacement done for $pattern"
"$TODO_FULL_SH" command replace $item "$newtodo"
