#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays detailed summary of tasks."
    echo "      If TERM specified, considers only tasks that contain TERM."
    echo ""
    exit
}

export TODOTXT_VERBOSE=0

listNum=$("$TODO_FULL_SH" -p -x command ls "$@" | wc -l) # All tasks, including future and done. 
doneNum=$("$TODO_FULL_SH" -p lsdo "$@" | wc -l)  # All tasks marked with "x". 
prioNum=$("$TODO_FULL_SH" -p lsp "$@" | wc -l)   # All prioritized tasks; includes future tasks depending on active filter. 
dueNum=$("$TODO_FULL_SH" -p lsdue "$@" | wc -l)  # All tasks that are due now. 
waitNum=$("$TODO_FULL_SH" -p lswait "$@" | wc -l) # All tasks marked with "w:..." marker; includes future tasks depending on active filter. 

# Undo the effect of a possible -x option; we need the filter to only show the
# due tasks. 
export TODOTXT_DISABLE_FILTER=0
# Also ensure that the correct filter is set. 
export TODOTXT_FINAL_FILTER="$HOME/.todo/futureTasks"
export post_filter_command="grep -v -e '^ *[0-9]\+ x ' -e ' w:[^ ]'"
activeNum=$("$TODO_FULL_SH" -p command ls "$@" | wc -l)    # All tasks not done, future, or waiting. 

futureNum=$((listNum - activeNum - waitNum - doneNum))  # All tasks that will only come due in the future. 

waitReasons=
if [ $waitNum -gt 0 ]; then
    waitReasons=$("$TODO_FULL_SH" listreasons "$@" | sed -n -e '1h' -e '1!H' -e '$g' -e '$s/\n/, /g' -e '$p')
fi

echo "TODO: ${listNum} tasks, ${prioNum} prioritized, ${dueNum} due"
echo "TODO: ${activeNum} available, ${waitNum} waiting, ${futureNum} future, ${doneNum} done"
if [ "$waitReasons" ]; then
    echo "TODO: waiting for $waitReasons"
fi
