#!/usr/bin/env bash
###############################################################################
##
# FILE:         uncomment
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 29-Dec-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2026 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)uncomment	$Id$	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-q] NR"
    echo "      Removes the done / trashed comment from task on line NR."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) [-q] NR"

: ${TODOTXT_COMMENT_SYMBOL:= => }
: ${TODOTXT_DISARMED_COMMENT_SYMBOL:=; }

isSilentAndQuery=
if [ "$1" = '-q' ]; then
    isSilentAndQuery=t
    shift
fi
item=$1; shift
[ $# -eq 0 ] || die "$errmsg"

getTodo "$item"
newtodo=${todo%%${TODOTXT_COMMENT_SYMBOL}*}
if [ "$newtodo" = "$todo" ]; then
    [ "$isSilentAndQuery" ] && exit 0

    [ $TODOTXT_VERBOSE -gt 0 ] && echo "$item $todo"
    die "TODO: Task $item does not contain a comment."
elif [ -z "$newtodo" ]; then
    die "TODO: Removal of comment would create empty task."
fi

if [ "$isSilentAndQuery" ]; then
    comment=${todo#*${TODOTXT_COMMENT_SYMBOL}}
    while :
    do
        if [ -n "$comment" ]; then
            answer="$(getKeyFromUser "Remove comment \"${comment}\", or disarm it by replacing \"${TODOTXT_COMMENT_SYMBOL// /}\" with \"${TODOTXT_DISARMED_COMMENT_SYMBOL// /}\"? (y/n/d) ")"
        else
            confirm 'Remove empty comment' \
                && break \
                || exit 4
        fi

        case "$answer" in
            d)  newtodo=${todo//${TODOTXT_COMMENT_SYMBOL}/${TODOTXT_DISARMED_COMMENT_SYMBOL}}; break;;
            n)  exit 4;;
            y)  break;;
        esac
    done
fi

"$TODO_FULL_SH" command replace $item "$newtodo"
