#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...]"
    echo "      Un-marks done task(s) on line ITEM# in todo.txt so that they become"
    echo "      active again."
    echo ""
    exit
}

shopt -s extglob
errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...]"

[ $# -eq 0 ] && die "$errmsg"
# Split multiple undo's, if comma seperated change to whitespace separated
# Loop the 'undo' function for each item
for item in `echo $* | tr ',' ' '`; do 
    [ -z "$item" ] && die "$errmsg"
    [[ "$item" = +([0-9]) ]] || die "$errmsg"

    todo=$(sed "$item!d" "$TODO_FILE")
    [ -z "$todo" ] && die "$item: No such task. Has it been archived?"

    # Check if this item has already been done. 
    if [ $(echo $todo | grep -c "^x ") -eq 1 ]; then
        # Remove done "x" marker and timestamp. 
        sed -i.bak $item"s|^x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} ||" "$TODO_FILE"
        [ $TODOTXT_VERBOSE -gt 0 ] && {
            sed "$item!d" "$TODO_FILE"
            echo "TODO: $item re-activated."
        }
    else
        echo "$item is not marked done. Has it been archived?"
    fi
done
