#!/bin/bash

action=$1
shift
item=$1
shift
param="$*"

shopt -s extglob
pattern=' \([uz]\):\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}' # not enforcing any particular format
syntax="$(basename $0) [ITEM# DATE|(none|never|off|del|rm) | del ITEM# | rm ITEM#]"
errmsg="usage: $TODO_SH $syntax"

usage()
{
	echo "    $syntax"
	echo "      Set, change or remove latest-until date of a task."
	echo "      If arguments are omitted, all tasks with an ultimate until-date are listed."
	echo "      Intended to be used with lsdue and colorFutureTasks."
	echo "      Example: $ $TODO_SH $(basename $0) 42 \"next week\""
	echo ""
	exit
}

list()
{
	post_filter_command="sed -e '/^ *[0-9]\+ x /d' -e '/$pattern/!d'"
	_list "$TODO_FILE"
}

getUnscheduledTask()
{
	getTodo "$1"

        # Keep existing type of marker; either "u:" or "z:". 
        marker=$(echo "$todo" | sed -ne "s/^.*${pattern}.*\$/\\1/p")
        marker=${marker:-u}

	# Remove threshold and priority. 
	todo=$(echo "$todo" | sed -e "s/${pattern}//g" -e "s/^([A-Z])* //") 
}

remove()
{
	getUnscheduledTask "$1"
	"$TODO_FULL_SH" command replace $1 "$todo" # N.B.: retains priority
}

replace()
{
	local item=$1
	local threshold=$2
	[ -z "$threshold" ] && die "$errmsg"
	date=$(date -d "$threshold" +%F) || return 1

	getUnscheduledTask "$item"
	"$TODO_FULL_SH" command replace $item "$todo ${marker}:$date"
}

[ "$action" = 'usage' ] && usage

if [ -z $item ]; then
	list
elif [ "$param" = 'del' -o "$param" = 'rm' -o "$param" = 'none' -o "$param" = 'never' -o "$param" = 'off' ]; then
	remove $item
elif [ "$item" = 'del' -o "$item" = 'rm' ]; then
	# Allow reverse syntax: todo.sh schedule ITEM# del, too.  
	remove $param
else
	replace $item "$param"
fi
