#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] \"REASON for Waiting\"[, REASON, ...]"
    echo "      Mark the task(s) on line ITEM# as blocked due to REASON."
    echo ""
    exit
}

die()
{
    echo "$*"
    exit 1
}
errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] \"REASON for Waiting\"[, REASON, ...]"

[ $# -eq 0 ] && die "$errmsg"

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items="$items $1"
    shift
done
[ "$items" -a $# -gt 0 ] || die "$errmsg"

waitReasons=
for waitReason
do
    # Enclose REASON's in parentheses if they consist of multiple words. 
    waitReasons=${waitReasons}${waitReasons:+ }w:$(echo "$waitReason" | sed -e '/[ \t]/s/.*/(\0)/')
done

# Split multiple wait's, if comma separated change to whitespace separated. 
for item in `echo $items | tr ',' ' '`; do 
    # Deprioritize in case it's currently prioritized. 
    if sed "$item!d" "$TODO_FILE" | grep -e '^(.) '; then
        "$TODO_FULL_SH" command depri $item || continue 
    fi

    "$TODO_FULL_SH" command append $item "$waitReasons"
done
