#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all prioritized and due tasks."
    echo "      If TERM specified, lists only tasks that contain TERM."
    echo ""
    exit
}

# Undo the effect of a possible -x option; we need the filter to only show the
# due tasks. 
export TODOTXT_DISABLE_FILTER=0

# Also ensure that the correct filter is set. 
export TODOTXT_FINAL_FILTER="$HOME/.todo/futureTasks"

# Consider only tasks that are not yet done, contain a priority or the "t:"
# schedule marker. The tasks are already numbered when the filter is applied, so
# there definitely is a space in front of the marker. 
export post_filter_command="grep -ve '^[0-9]\+ x ' | grep -e '([[:upper:]])' -e ' t:[0-9]\{2,4\}[^A-Za-z0-9][0-9]\{2,4\}[^A-Za-z0-9][0-9]\{2,4\}'" # not enforcing any particular format

_list "$TODO_FILE" "$@"
