#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [DATE] [TERM...]"
    echo "      Displays all prioritized and due tasks (based on DATE)."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

# Configuration to limit the priorities that are considered. 
: ${TODOTXT_WHAT_PRIORITIES:=A-Z}

export TODOTXT_LSDUE_TASKINCLUSION="-e '^ *[0-9]\+ ([${TODOTXT_WHAT_PRIORITIES}])'"
exec "$TODO_FULL_SH" lsdue "$@"
